name: belluga_now
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  auto_route: ^10.2.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.1
  free_map: ^2.5.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  get_it: ^8.2.0
  get_it_modular_with_auto_route: ^2.0.0
  intl: ^0.20.2
  geolocator: ^14.0.2
  package_info_plus: ^8.3.1
  platform_device_id_plus: ^1.0.7
  sentry_flutter: ^9.7.0
  slugify: ^2.0.0
  stream_value: ^0.0.6
  url_launcher: ^6.3.2
  share_plus: ^12.0.1
  map_launcher: ^4.4.2
  value_object_pattern: ^0.0.5
  video_player: ^2.10.0
  video_player_web_hls: ^1.3.0
  visibility_detector: ^0.4.0+2
  card_stack_swiper: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  auto_route_generator: ^10.2.5
  build_runner: ^2.10.1
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/mock/
  fonts:
    - family: BellugaNattive
      fonts:
        - asset: assets/fonts/BellugaNattive.ttf
