name: belluga_now
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  auto_route: ^11.1.0
  card_stack_swiper: ^1.0.2
  cupertino_icons: ^1.0.8
  crypto: ^3.0.5
  dio: ^5.9.0
  equatable: ^2.0.7
  event_tracker_handler: ^0.2.0
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  flutter_contacts: ^1.1.9+2
  flutter_html: ^3.0.0
  flutter_map: ^8.2.2
  free_map: ^2.5.0
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.2.1
  get_it: ^9.0.5
  get_it_modular_with_auto_route: ^2.2.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  latlong2: ^0.9.1
  map_launcher: ^4.4.2
  material_color_utilities: ^0.11.1
  meta: ^1.16.0
  package_info_plus: ^8.3.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  push_handler: ^0.2.0
  sentry_flutter: ^9.9.1
  share_plus: ^12.0.1
  stream_value: ^0.0.6
  slugify: ^2.0.0
  url_launcher: ^6.3.2
  uuid: ^4.5.1
  value_object_pattern: ^0.0.5
  video_player: ^2.10.0
  video_player_web_hls: ^1.3.0
  visibility_detector: ^0.4.0+2
  web: ^1.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  geolocator_platform_interface: ^4.1.1
  auto_route_generator: ^10.2.5
  build_runner: ^2.10.1
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/mock/
  fonts:
    - family: BooraIcons
      fonts:
        - asset: assets/fonts/BooraIcons.ttf
