name: unifast_portal
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  auto_route: ^10.1.0+1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.0
  get_it: ^8.0.3
  intl: ^0.20.2
  package_info_plus: ^8.3.0
  platform_device_id_plus: ^1.0.7
  sentry_flutter: ^9.1.0
  slugify: ^2.0.0
  stream_value: ^0.0.6
  url_launcher: ^6.3.1
  value_object_pattern: ^0.0.5
  video_player: ^2.10.0
  video_player_web_hls: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  auto_route_generator: ^10.2.3
  build_runner: ^2.5.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/mock/